##########################
#     SetHome GUI        #
##########################
# 作者: Beeted_
# 版本: 1.8.0

# 获取支持: https://discord.gg/3k4MbQ3KNv
# 高级插件 (支持我): https://builtbybit.com/resources/sethome-gui.51982
# 如果你喜欢这个插件，请在 Spigot 页面上给我好评，非常感谢！

# 自定义菜单。
menu:
  # 打开菜单的命令
  open-command: /home
  # 菜单标题
  gui-title: "&9&l家园菜单 &8⌂"
  # 玻璃面板颜色
  glass-pane-color: "GRAY"
  # 中心玻璃颜色
  center-glass-color: "LIGHT_BLUE"
  # 信息标题
  info-title: "&8❮❮❮ &7设置家园 &8| &7返回家园 &8❯❯❯"
  # 设置家园物品
  set-home-item:
    material: RED_BED
    display-name: "&7➤ &3&l设置家园"
    lore:
      - "&7使用此物品可以"
      - "&7设置你的家园并保存它"
      - "&7附带一个名字。"
      - ""
      - "&a(左键点击以设置家园)"
  # 查看已设家园物品
  your-homes-item:
    material: OAK_DOOR
    display-name: "&7➤ &e&l你的家园"
    lore:
      - "&7使用此物品可以"
      - "&7打开你的家园菜单"
      - "&7管理所有已设家园。"
      - ""
      - "&a(左键点击以打开菜单)"

homes-menu:
  # 家园菜单标题
  gui-title: "&9&l你的家园菜单 &8⌂"
  # 返回按钮文本
  go-back-item: "&c返回"
  # 关闭按钮文本
  close-item: "&4关闭"
  # 家园物品
  home-item:
    display-name: "&7&l家园 &8» &b%home%"
    # 可以在描述中使用 %home% 和 %world%
    lore:
      - "&c(右键点击以删除)"
      - "&a(左键点击以传送)"
  # 没有家园时显示的物品
  no-homes-item:
    display-name: "&c你还没有设置家园"
    lore:
      - "&7使用 /home 命令创建家园"

confirmation-menu:
  # 删除确认菜单标题
  gui-title: "&c确认删除"
  confirm-item:
    display-name: "&a确认"
  cancel-item:
    display-name: "&c取消"

# 自定义消息。
messages:
  home-established: "&a你的家园已成功设置！"
  not-established-home: "&c你还没有设置家园。"
  teleported: "&a你已传送到家园: &7%home%"
  home-not-found: "&4错误: 未找到家园坐标。"
  home-removed: "&c你的家园 &b%home% &c已被移除。"
  home-limit-reached: "&c你已达到允许的最大家园数量 (%limit%)。"
  home-exists: "&4已有同名家园，请选择其他名称。"
  enter-home-name: "&e请在聊天框中输入家园名称。如果你想取消，请输入 &7cancel"
  home-cancelled: "&c你已取消家园创建。"
  no-reload-permissions: "&c你没有权限重新加载插件！"
  plugin-reloaded: "&a插件已成功重新加载！"
  teleport-cooldown: "&a你将在 &7%seconds% &a秒后传送。不要移动。"
  teleport-in-progress: "&c你已经有正在进行的传送，请等待完成后再进行新的传送。"
  teleport-cancelled: "&c由于移动，你的传送已被取消。"
  world-not-found: "&c未找到要传送的世界。"

# 仅启用一个标题选项。
# 这些选项只有在冷却时间大于 0 时才能激活
titles:
  cooldown-title:
    enable: true
    teleport-title: "&a正在传送..."
    teleport-subtitle: "&e将在 %seconds% 秒后传送..."
  static-title:
    enable: false
    teleport-title: "&a正在传送..."
    teleport-subtitle: "&e将在 %seconds% 秒后传送..."

# 传送冷却时间（秒）
teleport-cooldown: 5
# 移动时取消传送
cancel-on-move: true
